config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :commands
  resources :message_logs
  resources :devices
  resources :units
  get 'control', to: 'control#index'
  get 'control/:id', to: 'control#index'
  get 'home/index'
  root 'home#index'
  resources :control do
    collection do
      get :get_device
       get 'get_device/:code', to: 'control#get_device'
       post :create_command
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message_log.rb
class MessageLog < ApplicationRecord
end

app/controllers/message_logs_controller.rb
class MessageLogsController < ApplicationController
  before_action :set_message_log, only: [:show, :edit, :update, :destroy]

  # GET /message_logs
  # GET /message_logs.json
  def index
    @message_logs = MessageLog.all
  end

  # GET /message_logs/1
  # GET /message_logs/1.json
  def show
  end

  # GET /message_logs/new
  def new
    @message_log = MessageLog.new
  end

  # GET /message_logs/1/edit
  def edit
  end

  # POST /message_logs
  # POST /message_logs.json
  def create
    @message_log = MessageLog.new(message_log_params)

    respond_to do |format|
      if @message_log.save
        format.html { redirect_to @message_log, notice: 'Message log was successfully created.' }
        format.json { render :show, status: :created, location: @message_log }
      else
        format.html { render :new }
        format.json { render json: @message_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /message_logs/1
  # PATCH/PUT /message_logs/1.json
  def update
    respond_to do |format|
      if @message_log.update(message_log_params)
        format.html { redirect_to @message_log, notice: 'Message log was successfully updated.' }
        format.json { render :show, status: :ok, location: @message_log }
      else
        format.html { render :edit }
        format.json { render json: @message_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /message_logs/1
  # DELETE /message_logs/1.json
  def destroy
    @message_log.destroy
    respond_to do |format|
      format.html { redirect_to message_logs_url, notice: 'Message log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message_log
      @message_log = MessageLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_log_params
      params.require(:message_log).permit(:content)
    end
end

app/helpers/message_logs_helper.rb
module MessageLogsHelper
end

app/views/message_logs/_form.html.erb
<%= form_with(model: message_log, local: true) do |form| %>
  <% if message_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message_log.errors.count, "error") %> prohibited this message_log from being saved:</h2>

      <ul>
      <% message_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/message_logs/edit.html.erb
<h1>Editing Message Log</h1>

<%= render 'form', message_log: @message_log %>

<%= link_to 'Show', @message_log %> |
<%= link_to 'Back', message_logs_path %>

app/views/message_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Message Logs</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @message_logs.each do |message_log| %>
      <tr>
        <td><%= message_log.content %></td>
        <td><%= link_to 'Show', message_log %></td>
        <td><%= link_to 'Edit', edit_message_log_path(message_log) %></td>
        <td><%= link_to 'Destroy', message_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message Log', new_message_log_path %>

app/views/message_logs/new.html.erb
<h1>New Message Log</h1>

<%= render 'form', message_log: @message_log %>

<%= link_to 'Back', message_logs_path %>

app/views/message_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message_log.content %>
</p>

<%= link_to 'Edit', edit_message_log_path(@message_log) %> |
<%= link_to 'Back', message_logs_path %>