config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :commands
  resources :message_logs
  resources :devices
  resources :units
  get 'control', to: 'control#index'
  get 'control/:id', to: 'control#index'
  get 'home/index'
  root 'home#index'
  resources :control do
    collection do
      get :get_device
       get 'get_device/:code', to: 'control#get_device'
       post :create_command
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/command.rb
class Command < ApplicationRecord
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :set_command, only: [:show, :edit, :update, :destroy]

  # GET /commands
  # GET /commands.json
  def index
    @commands = Command.all
  end

  # GET /commands/1
  # GET /commands/1.json
  def show
  end

  # GET /commands/new
  def new
    @command = Command.new
  end

  # GET /commands/1/edit
  def edit
  end

  # POST /commands
  # POST /commands.json
  def create
    @command = Command.new(command_params)

    respond_to do |format|
      if @command.save
        format.html { redirect_to @command, notice: 'Command was successfully created.' }
        format.json { render :show, status: :created, location: @command }
      else
        format.html { render :new }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commands/1
  # PATCH/PUT /commands/1.json
  def update
    respond_to do |format|
      if @command.update(command_params)
        format.html { redirect_to @command, notice: 'Command was successfully updated.' }
        format.json { render :show, status: :ok, location: @command }
      else
        format.html { render :edit }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command.destroy
    respond_to do |format|
      format.html { redirect_to commands_url, notice: 'Command was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_command
      @command = Command.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def command_params
      params.require(:command).permit(:code, :action, :command, :status)
    end
end

app/helpers/command_helper.rb
module CommandHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_form.html.erb
<%= form_with(model: command, local: true) do |form| %>
  <% if command.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(command.errors.count, "error") %> prohibited this command from being saved:</h2>

      <ul>
      <% command.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :action %>
    <%= form.number_field :action %>
  </div>

  <div class="field">
    <%= form.label :command %>
    <%= form.text_area :command %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/commands/edit.html.erb
<h1>Editing Command</h1>

<%= render 'form', command: @command %>

<%= link_to 'Show', @command %> |
<%= link_to 'Back', commands_path %>

app/views/commands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Commands</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Action</th>
      <th>Command</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commands.each do |command| %>
      <tr>
        <td><%= command.code %></td>
        <td><%= command.action %></td>
        <td><%= command.command %></td>
        <td><%= command.status %></td>
        <td><%= link_to 'Show', command %></td>
        <td><%= link_to 'Edit', edit_command_path(command) %></td>
        <td><%= link_to 'Destroy', command, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Command', new_command_path %>

app/views/commands/new.html.erb
<h1>New Command</h1>

<%= render 'form', command: @command %>

<%= link_to 'Back', commands_path %>

app/views/commands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @command.code %>
</p>

<p>
  <strong>Action:</strong>
  <%= @command.action %>
</p>

<p>
  <strong>Command:</strong>
  <%= @command.command %>
</p>

<p>
  <strong>Status:</strong>
  <%= @command.status %>
</p>

<%= link_to 'Edit', edit_command_path(@command) %> |
<%= link_to 'Back', commands_path %>